version: '3.3'

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  php:
    build:
      context: .docker/php
      dockerfile: php.dockerfile
    container_name: backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bmp_software
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  node:
    build:
      context: .docker/node
      dockerfile: node.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 5173:5173

  soketi:
    image: 'quay.io/soketi/soketi:0.17-16-alpine'
    environment:
      DEBUG: '1'
    ports:
      - 6001:6001
      - 9601:9601
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local